config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'cities#index' 

  resources :cities, only: [:show, :index]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, :code, :country, :lon, :lat, presence: true
  validates :code, length: { is: 6 }, numericality: { only_integer: true }
  validates :lon, :lat, numericality: true
  validates :country, length: { is: 2 }
  before_create :add_display

  def add_display
    self.display = false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  caches_page :show
  def index
    @city = City.where(display: true)
  end

  def show
    @city = City.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
require 'open_weather'

module CitiesHelper
  STRFTIME_TEMPLATE = '%d.%m.%y'.freeze
  ERROR_MSG = 'Something is wrong. Contact site administrator, please'.freeze
  TAG = :h4

  def temperature(code)
    weather = Rails.cache.fetch("#{code}_weather", expires_in: 10.minutes) do
      OpenWeather::Current.city_id(code, Rails.application.config.open_weather)
    end

    return ERROR_MSG unless weather['main']

    "today, #{Date.today.strftime(STRFTIME_TEMPLATE)}: #{weather['main']['temp'].to_i}°, #{weather['weather'][0]['description']}"
  end

  def forecast(code)
    weather = Rails.cache.fetch("#{code}_forecast", expires_in: 10.minutes) do
      OpenWeather::Forecast.city_id(code, Rails.application.config.open_weather)
    end
    return unless weather['list']
    list = weather['list']
    day = Date.today
    tags = []
    list.first(3).each do |data|
      day = day.next

      info = <<-STR.squish
        #{day.strftime(STRFTIME_TEMPLATE)}:
        #{data['weather'][0]['description']},
        #{data['main']['temp'].to_i}°
      STR

      tags << content_tag(TAG, info)
    end
    tags.join
  end

  def ya_map(lon, lat)
    "https://static-maps.yandex.ru/1.x/?ll=#{lon},#{lat}&l=map&size=300,300&z=7&lang=en_GB&pt=#{lon},#{lat},pm2blm"
  end
end

app/views/cities/index.html.erb
<div class="row">
  <% @city.each do |city| %>
    <div class="col-md-3">
      <div class="card">
        <div class="card-body text-center">
          <h4 class="card-title"><%= city.name.capitalize %></h4>
          <%= link_to "Check the weather", city_path(city), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cities/show.html.erb
<div class="media">
  <%= image_tag( ya_map(@city.lon,@city.lat), alt: "map", class: "mr-3") %>
    <div class="media-body">
    <h2 class="card-title"><%= @city.name.capitalize %></h2>
    <div class="temperature">
      <h1><%= temperature(@city.code) %><span class="degree"></span></h1>
      <div class="forecast" id="-forecast"><%= raw forecast(@city.code) %></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="clearfix d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h1 class="my-0 mr-md-auto font-weight-normal"><%= link_to 'The weather', root_path %></h1>
        <p class="navbar-text float-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </header>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>